module.exports.terms = ['Javascript',
'JQuery',
'High-level_programming_language',
'Dynamic_programming_language',
'Prototype-based_programming',
'Cascading_Style_Sheets',
'HTML',
'reactjs',
'angularjs',
'model-view-controller',
'Java_(programming_language)',
'C#',
'http',
'https',
'json',
'Server_(computing)',
'mongodb',
'MySQL',
'Relational_database_management_system',
'object-oriented programming',
'functional programming',
'imperative programming',
'internet',
'R_(programming_language)',
'data science',
'Immutable_object',
'Object_(computer_science)',
'Array_data_type',
'Computer_virus',
'Node.js',
'Express.js',
'Ember.js',
'Meteor_(web_framework)',
'Lodash',
'TypeScript',
'Npm_(software)',
'Webpack',
'ASP.NET',
'Open-source_model',
'Arduino',
'Medium_(website)',
'Hacker_News',
'TechCrunch',
'Hackathon',
'Vim_(text_editor)',
'Emacs',
'Atom_(text_editor)',
'Secure_Shell',
'Visual_Studio_Code',
'Git',
'Github',
'Ubuntu_(operating_system)'
]
